//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FluentPro.FluentPS.Psi.Exceptions.Faults;
using FluentPro.FluentPS.Psi.Model.DataSets;
using FluentPro.FluentPS.Psi.Model.Enums;
using FluentPro.FluentPS.Psi.Model.Messages;

namespace FluentPro.FluentPS.Psi.Interfaces.Psi
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/office/project/server/webservices/Admin/", ConfigurationName="Admin")]
    public interface IAdmin
    {
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetProjectPr" +
            "ofessionalMinimumBuildNumbers", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetProjectPr" +
            "ofessionalMinimumBuildNumbersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetPro" +
            "jectProfessionalMinimumBuildNumbersDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetPro" +
            "jectProfessionalMinimumBuildNumbersServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VersionsDataSet GetProjectProfessionalMinimumBuildNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetProjectPr" +
            "ofessionalMinimumBuildNumbers", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetProjectPr" +
            "ofessionalMinimumBuildNumbersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetPro" +
            "jectProfessionalMinimumBuildNumbersServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetPro" +
            "jectProfessionalMinimumBuildNumbersDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetProjectProfessionalMinimumBuildNumbers(VersionsDataSet versions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateUserSy" +
            "ncSetting", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateUserSy" +
            "ncSettingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "UserSyncSettingServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "UserSyncSettingDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateUserSyncSetting(UserSyncSettings userSyncSetting);
        
        // CODEGEN: Parameter 'replacementCharacter' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetADSyncRep" +
            "lacementCharacter", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetADSyncRep" +
            "lacementCharacterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetADS" +
            "yncReplacementCharacterServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetADS" +
            "yncReplacementCharacterDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SetADSyncReplacementCharacterResponse SetADSyncReplacementCharacter(SetADSyncReplacementCharacterRequest request);
        
        // CODEGEN: Parameter 'GetADSyncReplacementCharacterResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetADSyncRep" +
            "lacementCharacter", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetADSyncRep" +
            "lacementCharacterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetADS" +
            "yncReplacementCharacterServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetADS" +
            "yncReplacementCharacterDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GetADSyncReplacementCharacterResponse GetADSyncReplacementCharacter(GetADSyncReplacementCharacterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadFiscalPe" +
            "riods", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadFiscalPe" +
            "riodsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadFi" +
            "scalPeriodsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadFi" +
            "scalPeriodsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        FiscalPeriodDataSet ReadFiscalPeriods(int fiscalYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadAllDefin" +
            "edFiscalYears", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadAllDefin" +
            "edFiscalYearsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadAl" +
            "lDefinedFiscalYearsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadAl" +
            "lDefinedFiscalYearsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        FiscalYearDataSet ReadAllDefinedFiscalYears();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadTimeShee" +
            "tSettings", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadTimeShee" +
            "tSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadTi" +
            "meSheetSettingsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadTi" +
            "meSheetSettingsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimeSheetSettingsDataSet ReadTimeSheetSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateTimeSh" +
            "eetSettings", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateTimeSh" +
            "eetSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "TimeSheetSettingsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "TimeSheetSettingsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateTimeSheetSettings(TimeSheetSettingsDataSet dsDelta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/IsCachingEna" +
            "bled", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/IsCachingEna" +
            "bledResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/IsCach" +
            "ingEnabledDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/IsCach" +
            "ingEnabledServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool IsCachingEnabled(CacheType cacheType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/EnableCachin" +
            "g", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/EnableCachin" +
            "gResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Enable" +
            "CachingDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Enable" +
            "CachingServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void EnableCaching(CacheType cacheType, bool enable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadTimeshee" +
            "tManagers", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadTimeshee" +
            "tManagersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadTi" +
            "mesheetManagersServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadTi" +
            "mesheetManagersDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetManagersDataSet ReadTimesheetManagers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateTimesh" +
            "eetManagers", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateTimesh" +
            "eetManagersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "TimesheetManagersServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "TimesheetManagersDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateTimesheetManagers(TimesheetManagersDataSet managers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetActiveDir" +
            "ectorySyncEnterpriseResourcePoolSettings2", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetActiveDir" +
            "ectorySyncEnterpriseResourcePoolSettings2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetAct" +
            "iveDirectorySyncEnterpriseResourcePoolSettings2ServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetAct" +
            "iveDirectorySyncEnterpriseResourcePoolSettings2DefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ADSyncERPSettings2 GetActiveDirectorySyncEnterpriseResourcePoolSettings2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetActiveDir" +
            "ectorySyncEnterpriseResourcePoolSettings2", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetActiveDir" +
            "ectorySyncEnterpriseResourcePoolSettings2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetAct" +
            "iveDirectorySyncEnterpriseResourcePoolSettings2DefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetAct" +
            "iveDirectorySyncEnterpriseResourcePoolSettings2ServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetActiveDirectorySyncEnterpriseResourcePoolSettings2(ADSyncERPSettings2 settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetActiveDir" +
            "ectorySyncEnterpriseResourcePoolSettings", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetActiveDir" +
            "ectorySyncEnterpriseResourcePoolSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetAct" +
            "iveDirectorySyncEnterpriseResourcePoolSettingsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetAct" +
            "iveDirectorySyncEnterpriseResourcePoolSettingsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ADSyncERPSettings GetActiveDirectorySyncEnterpriseResourcePoolSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetActiveDir" +
            "ectorySyncEnterpriseResourcePoolSettings", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetActiveDir" +
            "ectorySyncEnterpriseResourcePoolSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetAct" +
            "iveDirectorySyncEnterpriseResourcePoolSettingsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetAct" +
            "iveDirectorySyncEnterpriseResourcePoolSettingsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetActiveDirectorySyncEnterpriseResourcePoolSettings(ADSyncERPSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetActiveDir" +
            "ectorySyncGroupSettings", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetActiveDir" +
            "ectorySyncGroupSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetAct" +
            "iveDirectorySyncGroupSettingsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetAct" +
            "iveDirectorySyncGroupSettingsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ADSyncGroupSettings GetActiveDirectorySyncGroupSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetActiveDir" +
            "ectorySyncGroupSettings", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetActiveDir" +
            "ectorySyncGroupSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetAct" +
            "iveDirectorySyncGroupSettingsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetAct" +
            "iveDirectorySyncGroupSettingsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetActiveDirectorySyncGroupSettings(ADSyncGroupSettings settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/QueueADSyncJ" +
            "ob", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/QueueADSyncJ" +
            "obResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/QueueA" +
            "DSyncJobServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/QueueA" +
            "DSyncJobDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueADSyncJob(System.Guid jobUid, bool erpSync, bool groupSync);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadLineClas" +
            "ses", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadLineClas" +
            "sesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadLi" +
            "neClassesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadLi" +
            "neClassesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetLineClassDataSet ReadLineClasses(LineClassType type, LineClassState classState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadPeriods", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadPeriodsR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadPe" +
            "riodsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadPe" +
            "riodsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimePeriodDataSet ReadPeriods(PeriodState p0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/PurgeTimeshe" +
            "etAuditLog", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/PurgeTimeshe" +
            "etAuditLogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/PurgeT" +
            "imesheetAuditLogDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/PurgeT" +
            "imesheetAuditLogServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void PurgeTimesheetAuditLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadTimeshee" +
            "tAuditLog", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadTimeshee" +
            "tAuditLogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadTi" +
            "mesheetAuditLogServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadTi" +
            "mesheetAuditLogDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetAuditExportDataSet ReadTimesheetAuditLog(System.DateTime auditStart, System.DateTime auditFinish, System.DateTime periodStart, System.DateTime periodFinish, AuditType auditType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateReport" +
            "ingPeriods", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateReport" +
            "ingPeriodsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "ReportingPeriodsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "ReportingPeriodsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateReportingPeriods(TimePeriodDataSet dsDelta, bool validationOnly);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateLineCl" +
            "asses", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateLineCl" +
            "assesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "LineClassesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "LineClassesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateLineClasses(TimesheetLineClassDataSet dsDelta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadPeriodsW" +
            "ithUnsubmittedTimesheet", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadPeriodsW" +
            "ithUnsubmittedTimesheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadPe" +
            "riodsWithUnsubmittedTimesheetDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadPe" +
            "riodsWithUnsubmittedTimesheetServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UnsubmittedTimesheetDataSet ReadPeriodsWithUnsubmittedTimesheet(System.Guid[] periods);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetNotificat" +
            "ionAdminInfoNoResult", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetNotificat" +
            "ionAdminInfoNoResultResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetNot" +
            "ificationAdminInfoNoResultDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetNot" +
            "ificationAdminInfoNoResultServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int SetNotificationAdminInfoNoResult(string WADMIN_ORG_EMAIL_ADDRESS, string WADMIN_NTFY_FROM_EMAIL, string WADMIN_NTFY_EMAIL_TRAILER, string WADMIN_SMTP_SERVER_NAME, int WADMIN_SMTP_SERVER_PORT, string WADMIN_EMAIL_CHARSET);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ListInstalle" +
            "dLanguages", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ListInstalle" +
            "dLanguagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ListIn" +
            "stalledLanguagesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ListIn" +
            "stalledLanguagesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int[] ListInstalledLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadServerVe" +
            "rsion", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadServerVe" +
            "rsionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadSe" +
            "rverVersionServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadSe" +
            "rverVersionDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet ReadServerVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadDepartme" +
            "nts", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadDepartme" +
            "ntsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadDe" +
            "partmentsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadDe" +
            "partmentsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DepartmentsDataSet ReadDepartments(int language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadDepartme" +
            "ntsByEntity", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadDepartme" +
            "ntsByEntityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadDe" +
            "partmentsByEntityDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadDe" +
            "partmentsByEntityServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DepartmentsDataSet ReadDepartmentsByEntity(System.Guid entityUid, System.Guid entityTypeUid, int language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetSingleCur" +
            "rencyEnforced", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetSingleCur" +
            "rencyEnforcedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetSin" +
            "gleCurrencyEnforcedDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetSin" +
            "gleCurrencyEnforcedServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool GetSingleCurrencyEnforced();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetSingleCur" +
            "rencyEnforced", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetSingleCur" +
            "rencyEnforcedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetSin" +
            "gleCurrencyEnforcedDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetSin" +
            "gleCurrencyEnforcedServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetSingleCurrencyEnforced(bool bEnforced);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetServerCur" +
            "rency", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetServerCur" +
            "rencyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetSer" +
            "verCurrencyDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetSer" +
            "verCurrencyServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetServerCurrency();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetServerCur" +
            "rency", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetServerCur" +
            "rencyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetSer" +
            "verCurrencyDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetSer" +
            "verCurrencyServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetServerCurrency(string sCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadStatusin" +
            "gSettings", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/ReadStatusin" +
            "gSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadSt" +
            "atusingSettingsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/ReadSt" +
            "atusingSettingsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusingSettingsDataSet ReadStatusingSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateStatus" +
            "ingSettings", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/UpdateStatus" +
            "ingSettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "StatusingSettingsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/Update" +
            "StatusingSettingsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateStatusingSettings(StatusingSettingsDataSet dsDelta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/QueueApplyRe" +
            "sourceCapacityTimeRange", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/QueueApplyRe" +
            "sourceCapacityTimeRangeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/QueueA" +
            "pplyResourceCapacityTimeRangeDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/QueueA" +
            "pplyResourceCapacityTimeRangeServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueApplyResourceCapacityTimeRange(System.Guid jobUid, bool forceFullSync);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetDatabaseT" +
            "imeout", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetDatabaseT" +
            "imeoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetDat" +
            "abaseTimeoutDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetDat" +
            "abaseTimeoutServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int GetDatabaseTimeout(DatabaseTimeoutType timeoutType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetDatabaseT" +
            "imeout", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetDatabaseT" +
            "imeoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetDat" +
            "abaseTimeoutDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetDat" +
            "abaseTimeoutServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetDatabaseTimeout(DatabaseTimeoutType timeoutType, int timeout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetCompatibi" +
            "lityMode", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/GetCompatibi" +
            "lityModeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetCom" +
            "patibilityModeDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/GetCom" +
            "patibilityModeServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int GetCompatibilityMode();

        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetCompatibi" +
            "lityMode", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Admin/SetCompatibi" +
            "lityModeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetCom" +
            "patibilityModeServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Admin/Admin/SetCom" +
            "patibilityModeDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetCompatibilityMode(int mode);
    }
}
