//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FluentPro.FluentPS.Psi.Exceptions.Faults;
using FluentPro.FluentPS.Psi.Model.DataSets;
using FluentPro.FluentPS.Psi.Model.Enums;
using FluentPro.FluentPS.Psi.Model.Messages;

namespace FluentPro.FluentPS.Psi.Interfaces.Psi
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
        "/", ConfigurationName="ObjectLinkProvider")]
    public interface IObjectLinkProvider
    {
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadLinkedWebObjects", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadLinkedWebObjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadLinkedWebObjectsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadLinkedWebObjectsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ObjectLinkProviderDataSet ReadLinkedWebObjects(System.Guid objectUid, int filterWebObjectTypes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadProjectLinkedWebObjects", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadProjectLinkedWebObjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadProjectLinkedWebObjectsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadProjectLinkedWebObjectsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ObjectLinkProviderDataSet ReadProjectLinkedWebObjects(System.Guid projectUid, int filterWebObjectTypes, bool includeTaskLinkedObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadTaskLinkedWebObjects", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadTaskLinkedWebObjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadTaskLinkedWebObjectsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadTaskLinkedWebObjectsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ObjectLinkProviderDataSet ReadTaskLinkedWebObjects(System.Guid taskUid, int filterWebObjectTypes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadSharePointItemLinkedWebObjects", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadSharePointItemLinkedWebObjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadSharePointItemLinkedWebObjectsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadSharePointItemLinkedWebObjectsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ObjectLinkProviderDataSet ReadSharePointItemLinkedWebObjects(int tpId, System.Guid sharePointListName, int filterWebObjectTypes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadWebObject", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadWebObjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadWebObjectServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadWebObjectDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ObjectLinkProviderDataSet ReadWebObject(System.Guid webObjectUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadProjectWebObject", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadProjectWebObjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadProjectWebObjectServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadProjectWebObjectDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ObjectLinkProviderDataSet ReadProjectWebObject(System.Guid projectUid, bool includeTaskObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadTaskWebObject", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadTaskWebObjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadTaskWebObjectServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadTaskWebObjectDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ObjectLinkProviderDataSet ReadTaskWebObject(System.Guid taskUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadSharePointWebObject", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadSharePointWebObjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadSharePointWebObjectDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadSharePointWebObjectServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ObjectLinkProviderDataSet ReadSharePointWebObject(int tpId, System.Guid sharePointListName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadObjectByDescription", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadObjectByDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadObjectByDescriptionServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadObjectByDescriptionDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ObjectLinkProviderDataSet ReadObjectByDescription(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/CreateWebObjectLinksByGuid", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/CreateWebObjectLinksByGuidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/CreateWebObjectLinksByGuidServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/CreateWebObjectLinksByGuidDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int CreateWebObjectLinksByGuid(System.Guid webObjectUid, System.Guid[] webObjectUidsToLinkTo, WebObjectLinkType[] linkTypes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/CreateWebObjectLinks", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/CreateWebObjectLinksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/CreateWebObjectLinksDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/CreateWebObjectLinksServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int CreateWebObjectLinks(ObjectLinkProviderDataSet primaryDataSet, ObjectLinkProviderDataSet linkDataSet, WebObjectLinkType[] linkTypes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadOrCreateWebObjects", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadOrCreateWebObjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadOrCreateWebObjectsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadOrCreateWebObjectsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ReadOrCreateWebObjectsResponse ReadOrCreateWebObjects(ReadOrCreateWebObjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/DeleteWebObjectLink", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/DeleteWebObjectLinkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/DeleteWebObjectLinkServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/DeleteWebObjectLinkDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int DeleteWebObjectLink(System.Guid webObjectUid1, System.Guid webObjectUid2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/DeleteProjectWebObjects", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/DeleteProjectWebObjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/DeleteProjectWebObjectsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/DeleteProjectWebObjectsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteProjectWebObjects(System.Guid projectUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/DeleteWebObject", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/DeleteWebObjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/DeleteWebObjectDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/DeleteWebObjectServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteWebObject(System.Guid webObjectUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadObjectLinkType", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ReadObjectLinkTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadObjectLinkTypeServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/ObjectLinkProvider" +
            "/ObjectLinkProvider/ReadObjectLinkTypeDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WebObjectLinkType ReadObjectLinkType(System.Guid object1, System.Guid object2);
    }
}
