//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FluentPro.FluentPS.Psi.Exceptions.Faults;
using FluentPro.FluentPS.Psi.Model.DataSets;

namespace FluentPro.FluentPS.Psi.Interfaces.Psi
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
        "", ConfigurationName="PortfolioAnalyses")]
    public interface IPortfolioAnalyses
    {
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadOptimizerSolutionList", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadOptimizerSolutionListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadOptimizerSolutionListDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadOptimizerSolutionListServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        OptimizerSolutionDataSet ReadOptimizerSolutionList(System.Guid analysisUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadOptimizerSolution", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadOptimizerSolutionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadOptimizerSolutionServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadOptimizerSolutionDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        OptimizerSolutionDataSet ReadOptimizerSolution(System.Guid solutionUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueDeleteOptimizerSolutions", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueDeleteOptimizerSolutionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueDeleteOptimizerSolutionsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueDeleteOptimizerSolutionsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueDeleteOptimizerSolutions(System.Guid[] solutionUids, System.Guid[] jobUids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueCreateOptimizerSolution", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueCreateOptimizerSolutionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueCreateOptimizerSolutionDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueCreateOptimizerSolutionServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueCreateOptimizerSolution(System.Guid analysisUid, OptimizerSolutionDataSet solutionDS, System.Guid jobUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadAnalysis", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadAnalysisResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadAnalysisServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadAnalysisDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AnalysisDataSet ReadAnalysis(System.Guid analysisUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadAnalysisList", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadAnalysisListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadAnalysisListServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadAnalysisListDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AnalysisDataSet ReadAnalysisList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "CreateDependency", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "CreateDependencyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/CreateDependencyDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/CreateDependencyServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        OptimizerDependencyDataSet CreateDependency(OptimizerDependencyDataSet dependencyDataSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadDependency", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadDependencyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadDependencyServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadDependencyDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        OptimizerDependencyDataSet ReadDependency(System.Guid dependencyUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "DeleteDependencies", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "DeleteDependenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/DeleteDependenciesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/DeleteDependenciesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteDependencies(System.Guid[] dependencyUids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "UpdateDependency", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "UpdateDependencyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/UpdateDependencyDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/UpdateDependencyServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        OptimizerDependencyDataSet UpdateDependency(OptimizerDependencyDataSet dependencyDataSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadDependencyList", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadDependencyListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadDependencyListDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadDependencyListServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        OptimizerDependencyDataSet ReadDependencyList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadPlannerSolutionList", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadPlannerSolutionListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadPlannerSolutionListServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadPlannerSolutionListDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PlannerSolutionDataSet ReadPlannerSolutionList(System.Guid parentSolutionUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadPlannerSolution", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "ReadPlannerSolutionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadPlannerSolutionServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/ReadPlannerSolutionDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PlannerSolutionDataSet ReadPlannerSolution(System.Guid solutionUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueDeletePlannerSolutions", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueDeletePlannerSolutionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueDeletePlannerSolutionsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueDeletePlannerSolutionsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueDeletePlannerSolutions(System.Guid[] solutionUIDs, System.Guid[] jobUids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueCreatePlannerSolution", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueCreatePlannerSolutionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueCreatePlannerSolutionServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueCreatePlannerSolutionDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueCreatePlannerSolution(PlannerSolutionDataSet plannerSolutionDataSet, System.Guid jobUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueDeleteAnalyses", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueDeleteAnalysesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueDeleteAnalysesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueDeleteAnalysesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueDeleteAnalyses(System.Guid[] analysesUIDs, System.Guid[] jobUids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueCreateAnalysis", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueCreateAnalysisResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueCreateAnalysisServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueCreateAnalysisDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueCreateAnalysis(AnalysisDataSet analysisDataSet, System.Guid jobUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueUpdateAnalysis", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "QueueUpdateAnalysisResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueUpdateAnalysisDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/QueueUpdateAnalysisServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueUpdateAnalysis(AnalysisDataSet analysisDataSet, bool forceRefreshPlannerData, System.Guid jobUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "CommitOptimizerSolution", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "CommitOptimizerSolutionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/CommitOptimizerSolutionDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/CommitOptimizerSolutionServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CommitOptimizerSolution(System.Guid solutionUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "CommitPlannerSolution", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "CommitPlannerSolutionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/CommitPlannerSolutionDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/PortfolioAnalyses/" +
            "PortfolioAnalyses/CommitPlannerSolutionServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CommitPlannerSolution(System.Guid solutionUid);
    }
}
