//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FluentPro.FluentPS.Psi.Exceptions.Faults;
using FluentPro.FluentPS.Psi.Model.DataSets;
using FluentPro.FluentPS.Psi.Model.Enums;
using FluentPro.FluentPS.Psi.Model.Messages;

namespace FluentPro.FluentPS.Psi.Interfaces.Psi
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/office/project/server/webservices/Statusing/", ConfigurationName="Statusing")]
    public interface IStatusing
    {
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/SubmitSt" +
            "atusForResource", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/SubmitSt" +
            "atusForResourceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/SubmitStatusForResourceServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/SubmitStatusForResourceDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SubmitStatusForResource(System.Guid resid, System.Guid[] updateGuids, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/CreateNe" +
            "wAssignmentWithWork", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/CreateNe" +
            "wAssignmentWithWorkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/CreateNewAssignmentWithWorkServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/CreateNewAssignmentWithWorkDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CreateNewAssignmentWithWork(string sName, System.Guid projGuid, System.Guid taskGuid, System.Guid assnGuid, System.Guid sumTaskGuid, System.DateTime dtStart, System.DateTime dtFinish, double actWork, bool fMilestone, bool fAddToTimesheet, bool fSubmit, string sComment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadTask" +
            "DataForAwiopJSON", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadTask" +
            "DataForAwiopJSONResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadTaskDataForAwiopJSONDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadTaskDataForAwiopJSONServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string ReadTaskDataForAwiopJSON(System.Guid assnUid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/DeleteSt" +
            "atusingInformationForProject", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/DeleteSt" +
            "atusingInformationForProjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/DeleteStatusingInformationForProjectDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/DeleteStatusingInformationForProjectServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteStatusingInformationForProject(System.Guid[] projectID, System.DateTime minDate, System.DateTime maxDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usApprovalsSubmitted", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usApprovalsSubmittedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusApprovalsSubmittedServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusApprovalsSubmittedDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusApprovalDataSet ReadStatusApprovalsSubmitted(bool includeTasks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadTran" +
            "sactionDetails", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadTran" +
            "sactionDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadTransactionDetailsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadTransactionDetailsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusApprovalTransactionDetailsDataSet ReadTransactionDetails(System.Guid updateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usApprovalDetails", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usApprovalDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusApprovalDetailsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusApprovalDetailsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusApprovalTransactionDetailsDataSet ReadStatusApprovalDetails(System.Guid assignmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/UpdateSt" +
            "atusApprovals", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/UpdateSt" +
            "atusApprovalsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/UpdateStatusApprovalsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/UpdateStatusApprovalsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateStatusApprovals(StatusApprovalDataSet dataSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/QueueApp" +
            "lyStatusApprovals", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/QueueApp" +
            "lyStatusApprovalsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/QueueApplyStatusApprovalsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/QueueApplyStatusApprovalsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusTransactionDataSet QueueApplyStatusApprovals(System.Guid jobID, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usApprovalsInProcess", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usApprovalsInProcessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusApprovalsInProcessServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusApprovalsInProcessDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusApprovalDataSet ReadStatusApprovalsInProcess(System.Guid userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/DeleteSt" +
            "atusApprovalHistories", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/DeleteSt" +
            "atusApprovalHistoriesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/DeleteStatusApprovalHistoriesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/DeleteStatusApprovalHistoriesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteStatusApprovalHistories(System.Guid[] historyUids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/UpdateSt" +
            "atus", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/UpdateSt" +
            "atusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/UpdateStatusServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/UpdateStatusDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateStatus(string changexml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/SubmitSt" +
            "atus", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/SubmitSt" +
            "atusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/SubmitStatusDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/SubmitStatusServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SubmitStatus(System.Guid[] updateGuids, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/SetAssig" +
            "nmentWorkData", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/SetAssig" +
            "nmentWorkDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/SetAssignmentWorkDataServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/SetAssignmentWorkDataDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int SetAssignmentWorkData(string changeXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/CreateNe" +
            "wAssignment", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/CreateNe" +
            "wAssignmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/CreateNewAssignmentServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/CreateNewAssignmentDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CreateNewAssignment(string sName, System.Guid projGuid, System.Guid taskGuid, System.Guid assnGuid, System.Guid sumTaskGuid, System.DateTime dtStart, System.DateTime dtFinish, bool fAddToTimesheet, bool fSubmit, string sComment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadAssi" +
            "gnmentDependencies", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadAssi" +
            "gnmentDependenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadAssignmentDependenciesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadAssignmentDependenciesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusingAssignmentDependenciesDataSet ReadAssignmentDependencies(System.Guid p0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadSumm" +
            "aryTaskPath", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadSumm" +
            "aryTaskPathResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadSummaryTaskPathServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadSummaryTaskPathDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        SummaryTaskPathDataSet ReadSummaryTaskPath(System.Guid p0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "us", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusingDataSet ReadStatus(System.Guid assnid, System.DateTime mindate, System.DateTime maxdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadTeam" +
            "Status", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadTeam" +
            "StatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadTeamStatusServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadTeamStatusDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusingDataSet ReadTeamStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usTimephasedData", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usTimephasedDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusTimephasedDataServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusTimephasedDataDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusingTimephasedActualsDataSet ReadStatusTimephasedData(System.Guid projid, System.Guid assnid, System.DateTime start, System.DateTime end, long intervalInMinutes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Delegate" +
            "Assignments", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Delegate" +
            "AssignmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/DelegateAssignmentsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/DelegateAssignmentsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DelegateAssignments(DelegationDataSet assignmentDataSet, System.DateTime startDate, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ImportTi" +
            "mesheet", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ImportTi" +
            "mesheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ImportTimesheetDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ImportTimesheetServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ImportTimesheet(System.Guid periodUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/QueueLoc" +
            "kDownTasks", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/QueueLoc" +
            "kDownTasksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/QueueLockDownTasksDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/QueueLockDownTasksServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueLockDownTasks(System.Guid jobUid, System.Guid projguid, ProjectDataSet delta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadAssi" +
            "gnments", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadAssi" +
            "gnmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadAssignmentsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadAssignmentsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusingAssignmentsDataSet ReadAssignments(System.Guid[] assnUIDs);
        
        // CODEGEN: Parameter 'ReadPublishedNoteForTaskResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadPubl" +
            "ishedNoteForTask", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadPubl" +
            "ishedNoteForTaskResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadPublishedNoteForTaskServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadPublishedNoteForTaskDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ReadPublishedNoteForTaskResponse ReadPublishedNoteForTask(ReadPublishedNoteForTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadAssi" +
            "gnmentHistory", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadAssi" +
            "gnmentHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadAssignmentHistoryDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadAssignmentHistoryServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AssnHistoryDataSet ReadAssignmentHistory(System.Guid itemid, AssnHistoryItemType itemtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadMySc" +
            "hedule", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadMySc" +
            "heduleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadMyScheduleDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadMyScheduleServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ScheduleDataSet ReadMySchedule(System.DateTime start, System.DateTime finish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadAssi" +
            "gnmentsForDelegation", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadAssi" +
            "gnmentsForDelegationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadAssignmentsForDelegationServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadAssignmentsForDelegationDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DelegationDataSet ReadAssignmentsForDelegation(DelegationFilterType filter, System.Guid filterParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadImpo" +
            "rtTimesheetData", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadImpo" +
            "rtTimesheetDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadImportTimesheetDataServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadImportTimesheetDataDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ImportTimesheetDataSet ReadImportTimesheetData(System.Guid periodUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/GetNewTa" +
            "skCount", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/GetNewTa" +
            "skCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/GetNewTaskCountDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/GetNewTaskCountServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int GetNewTaskCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usForResource", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/Statusing/ReadStat" +
            "usForResourceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusForResourceServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/Statusing/Statusin" +
            "g/ReadStatusForResourceDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        StatusingDataSet ReadStatusForResource(System.Guid resid, System.Guid assnid, System.DateTime mindate, System.DateTime maxdate);   
    }
}
