//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FluentPro.FluentPS.Psi.Exceptions.Faults;
using FluentPro.FluentPS.Psi.Model.DataSets;
using FluentPro.FluentPS.Psi.Model.Enums;
using FluentPro.FluentPS.Psi.Model.Messages;

namespace FluentPro.FluentPS.Psi.Interfaces.Psi
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/", ConfigurationName="TimeSheet")]
    public interface ITimeSheet
    {
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetList", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetListServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetListDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetListDataSet ReadTimesheetList(System.Guid resUID, System.DateTime startDate, System.DateTime finishDate, int select);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetByPeriod", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetByPeriodResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetByPeriodServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetByPeriodDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetDataSet ReadTimesheetByPeriod(System.Guid resUID, System.Guid periodUID, Navigation select);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheet", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetDataSet ReadTimesheet(System.Guid tsUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetApprovers", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetApproversResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetApproversDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetApproversServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ResourceDataSet ReadTimesheetApprovers(System.Guid tsUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadReso" +
            "urceLateTimesheets", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadReso" +
            "urceLateTimesheetsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadResourceLateTimesheetsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadResourceLateTimesheetsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetListDataSet ReadResourceLateTimesheets(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadLate" +
            "Timesheets", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadLate" +
            "TimesheetsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadLateTimesheetsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadLateTimesheetsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetListDataSet ReadLateTimesheets(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueDel" +
            "eteTimesheet", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueDel" +
            "eteTimesheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueDeleteTimesheetDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueDeleteTimesheetServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueDeleteTimesheet(System.Guid jobUID, System.Guid tsUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueSub" +
            "mitTimesheet", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueSub" +
            "mitTimesheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueSubmitTimesheetDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueSubmitTimesheetServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueSubmitTimesheet(System.Guid jobUID, System.Guid tsUID, System.Guid approverUID, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueRev" +
            "iewTimesheet", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueRev" +
            "iewTimesheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueReviewTimesheetDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueReviewTimesheetServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueReviewTimesheet(System.Guid jobUID, System.Guid tsUID, System.Guid nextApproverUID, string comment, Action action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueRec" +
            "allTimesheet", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueRec" +
            "allTimesheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueRecallTimesheetDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueRecallTimesheetServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueRecallTimesheet(System.Guid jobUID, System.Guid tsUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueUpd" +
            "ateTimesheet", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueUpd" +
            "ateTimesheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueUpdateTimesheetDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueUpdateTimesheetServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueUpdateTimesheet(System.Guid jobUID, System.Guid tsUID, TimesheetDataSet dsDelta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ApproveN" +
            "onProjectTime", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ApproveN" +
            "onProjectTimeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ApproveNonProjectTimeDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ApproveNonProjectTimeServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ApproveNonProjectTime(System.Guid[] approvedTimesheetLines, System.Guid[] rejectedTimesheetLines);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/PrepareT" +
            "imesheetLine", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/PrepareT" +
            "imesheetLineResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/PrepareTimesheetLineServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/PrepareTimesheetLineDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PrepareTimesheetLineResponse PrepareTimesheetLine(PrepareTimesheetLineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/SubmitTi" +
            "mesheetLines", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/SubmitTi" +
            "mesheetLinesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/SubmitTimesheetLinesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/SubmitTimesheetLinesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SubmitTimesheetLines(System.Guid[] timesheetLines, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/CreateTi" +
            "mesheet", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/CreateTi" +
            "mesheetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/CreateTimesheetDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/CreateTimesheetServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CreateTimesheet(TimesheetDataSet dsDelta, PreloadType preloadType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetsPendingApproval", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetsPendingApprovalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetsPendingApprovalDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetsPendingApprovalServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetListDataSet ReadTimesheetsPendingApproval(System.DateTime start, System.DateTime finish, System.Guid[] resUIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadRevi" +
            "ewedTimesheets", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadRevi" +
            "ewedTimesheetsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadReviewedTimesheetsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadReviewedTimesheetsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetListDataSet ReadReviewedTimesheets(System.DateTime start, System.DateTime finish, System.Guid[] resUIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetsToAdjust", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadTime" +
            "sheetsToAdjustResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetsToAdjustServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadTimesheetsToAdjustDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        TimesheetListDataSet ReadTimesheetsToAdjust(System.DateTime start, System.DateTime finish, System.Guid[] resUIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueCle" +
            "anUpTimesheets", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/QueueCle" +
            "anUpTimesheetsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueCleanUpTimesheetsServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/QueueCleanUpTimesheetsDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueCleanUpTimesheets(System.DateTime start, System.DateTime finish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadProj" +
            "ectTimesheetLines", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ReadProj" +
            "ectTimesheetLinesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadProjectTimesheetLinesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ReadProjectTimesheetLinesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ProjectTimesheetLinesDataSet ReadProjectTimesheetLines(System.Guid periodUID, ProjectTimesheetLineQueryType qryType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ApproveP" +
            "rojectTimesheetLines", ReplyAction="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/ApproveP" +
            "rojectTimesheetLinesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServerExecutionFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ApproveProjectTimesheetLinesServerExecutionFaultFault", Name="ServerExecutionFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof(DefaultServerFault), Action="http://schemas.microsoft.com/office/project/server/webservices/TimeSheet/TimeShee" +
            "t/ApproveProjectTimesheetLinesDefaultServerFaultFault", Name="DefaultServerFault", Namespace="http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ApproveProjectTimesheetLines(System.Guid[] approvedTimesheetLines, System.Guid[] rejectedTimesheetLines, string comment);
    }
}
