//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.ServiceModel;
using FluentPro.FluentPS.Psi.Exceptions.Faults;
using FluentPro.FluentPS.Psi.Model.DataSets;

namespace FluentPro.FluentPS.Psi.Interfaces.Psi
{
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName = "View", Namespace = "http://schemas.microsoft.com/office/project/server/webservices/View/")]
    public interface IView
    {
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/CopyViewReportsDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [XmlSerializerFormat]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/CopyViewReports", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/CopyViewReportsResponse")]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/CopyViewReportsServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        int CopyViewReports(Guid view_uid, string view_new_name);

        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/DeleteViewReportsServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/DeleteViewReports", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/DeleteViewReportsResponse")]
        [XmlSerializerFormat]
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/DeleteViewReportsDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        int DeleteViewReports(Guid view_uid);

        [XmlSerializerFormat]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadWorkFieldsServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadWorkFieldsDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadWorkFields", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadWorkFieldsResponse")]
        ViewFieldsDataSet ReadWorkFields();

        [XmlSerializerFormat]
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadTimeSheetFieldsDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadTimeSheetFieldsServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadTimeSheetFields", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadTimeSheetFieldsResponse")]
        ViewFieldsDataSet ReadTimeSheetFields();

        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadProjectFieldsDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadProjectFieldsServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [XmlSerializerFormat]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadProjectFields", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadProjectFieldsResponse")]
        ViewFieldsDataSet ReadProjectFields(Guid table_uid);

        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadPortfolioFieldsDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [XmlSerializerFormat]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadPortfolioFieldsServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadPortfolioFields", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadPortfolioFieldsResponse")]
        ViewFieldsDataSet ReadPortfolioFields();

        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadResourceCenterFields", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadResourceCenterFieldsResponse")]
        [XmlSerializerFormat]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadResourceCenterFieldsServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadResourceCenterFieldsDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        ViewFieldsDataSet ReadResourceCenterFields();

        [XmlSerializerFormat]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadResourceAssignmentFields", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadResourceAssignmentFieldsResponse")]
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadResourceAssignmentFieldsDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadResourceAssignmentFieldsServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        ViewFieldsDataSet ReadResourceAssignmentFields();

        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadResourcePlanFieldsDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadResourcePlanFields", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadResourcePlanFieldsResponse")]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadResourcePlanFieldsServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [XmlSerializerFormat]
        ViewFieldsDataSet ReadResourcePlanFields();

        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadGanttSchemesServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadGanttSchemes", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadGanttSchemesResponse")]
        [XmlSerializerFormat]
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadGanttSchemesDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        GanttSchemesDataSet ReadGanttSchemes(int scheme_type);

        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadViewSummaries", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadViewSummariesResponse")]
        [XmlSerializerFormat]
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadViewSummariesDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadViewSummariesServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        PWAViewReportsDataSet ReadViewSummaries();

        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadView", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadViewResponse")]
        [XmlSerializerFormat]
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadViewDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadViewServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        PWAViewReportsDataSet ReadView(Guid view_uid);

        [XmlSerializerFormat]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadTimesheetView", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/ReadTimesheetViewResponse")]
        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadTimesheetViewDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/ReadTimesheetViewServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        PWAViewReportsDataSet ReadTimesheetView(Guid ts_uid, Guid view_uid);

        [FaultContract(typeof(DefaultServerFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/UpdateViewDefaultServerFaultFault", Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [FaultContract(typeof(ServerExecutionFault), Action = "http://schemas.microsoft.com/office/project/server/webservices/View/View/UpdateViewServerExecutionFaultFault", Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [XmlSerializerFormat]
        [OperationContract(Action = "http://schemas.microsoft.com/office/project/server/webservices/View/UpdateView", ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/View/UpdateViewResponse")]
        void UpdateView(PWAViewReportsDataSet dsNew);
    }
}
