//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FluentPro.FluentPS.Psi.Exceptions.Faults;
using FluentPro.FluentPS.Psi.Model.DataSets;
using FluentPro.FluentPS.Psi.Model.Messages;

namespace FluentPro.FluentPS.Psi.Interfaces.Psi
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(
        Namespace = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/",
        ConfigurationName = "Workflow")]
    public interface IWorkflow
    {

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                     "lowPhaseList",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                          "lowPhaseListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowPhaseListServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowPhaseListDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet ReadWorkflowPhaseList();


        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                     "lowPhase",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                          "lowPhaseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowPhaseServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowPhaseDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet ReadWorkflowPhase(System.Guid workflowPhaseUid);
        
        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/CreateWor" +
                     "kflowPhase",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/CreateWor" +
                          "kflowPhaseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "CreateWorkflowPhaseServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "CreateWorkflowPhaseDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CreateWorkflowPhase(WorkflowDataSet workflowDS);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdateWor" +
                     "kflowPhase",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdateWor" +
                          "kflowPhaseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateWorkflowPhaseServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateWorkflowPhaseDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet UpdateWorkflowPhase(WorkflowDataSet workflowDS);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/DeleteWor" +
                     "kflowPhases",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/DeleteWor" +
                          "kflowPhasesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "DeleteWorkflowPhasesServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "DeleteWorkflowPhasesDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteWorkflowPhases(System.Guid[] workflowPhaseUid);
        
        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                     "lowStageList",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                          "lowStageListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowStageListServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowStageListDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet ReadWorkflowStageList();

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                     "lowStage",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                          "lowStageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowStageServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowStageDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet ReadWorkflowStage(System.Guid workflowStageUid);
        
        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/CreateWor" +
                     "kflowStage",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/CreateWor" +
                          "kflowStageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "CreateWorkflowStageServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "CreateWorkflowStageDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CreateWorkflowStage(WorkflowDataSet workflowDS);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdateWor" +
                     "kflowStage",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdateWor" +
                          "kflowStageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateWorkflowStageServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateWorkflowStageDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet UpdateWorkflowStage(WorkflowDataSet workflowDS);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/DeleteWor" +
                     "kflowStages",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/DeleteWor" +
                          "kflowStagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "DeleteWorkflowStagesServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "DeleteWorkflowStagesDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteWorkflowStages(System.Guid[] workflowStageUid);
        
        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/RunProjec" +
                     "tWorkflow",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/RunProjec" +
                          "tWorkflowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "RunProjectWorkflowDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "RunProjectWorkflowServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void RunProjectWorkflow(System.Guid projectUid);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                     "lows",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                          "lowsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowsDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowsServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet ReadWorkflows();

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                     "lowStatus",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                          "lowStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowStatusServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowStatusDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet ReadWorkflowStatus(System.Guid projUid, bool readAllStagesAndPhases);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                     "lowProxyUser",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadWorkf" +
                          "lowProxyUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowProxyUserServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadWorkflowProxyUserDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ResourceDataSet ReadWorkflowProxyUser();

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdateWor" +
                     "kflowProxyUser",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdateWor" +
                          "kflowProxyUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateWorkflowProxyUserServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateWorkflowProxyUserDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateWorkflowProxyUser(System.Guid resUid);
        
        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadEnter" +
                     "priseProjectTypeList",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadEnter" +
                          "priseProjectTypeListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadEnterpriseProjectTypeListServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadEnterpriseProjectTypeListDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet ReadEnterpriseProjectTypeList();
        
        // CODEGEN: Parameter 'departmentUid' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadEnter" +
                     "priseProjectTypeListByDepartment",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadEnter" +
                          "priseProjectTypeListByDepartmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadEnterpriseProjectTypeListByDepartmentServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadEnterpriseProjectTypeListByDepartmentDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        ReadEnterpriseProjectTypeListByDepartmentResponse ReadEnterpriseProjectTypeListByDepartment(
            ReadEnterpriseProjectTypeListByDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadEnter" +
                     "priseProjectType",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadEnter" +
                          "priseProjectTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadEnterpriseProjectTypeServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadEnterpriseProjectTypeDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet ReadEnterpriseProjectType(System.Guid enterpriseProjectTypeUid);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/CreateEnt" +
                     "erpriseProjectType",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/CreateEnt" +
                          "erpriseProjectTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "CreateEnterpriseProjectTypeServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "CreateEnterpriseProjectTypeDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CreateEnterpriseProjectType(WorkflowDataSet workflowDS);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdateEnt" +
                     "erpriseProjectType",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdateEnt" +
                          "erpriseProjectTypeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateEnterpriseProjectTypeDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateEnterpriseProjectTypeServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet UpdateEnterpriseProjectType(WorkflowDataSet workflowDS);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/DeleteEnt" +
                     "erpriseProjectTypes",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/DeleteEnt" +
                          "erpriseProjectTypesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "DeleteEnterpriseProjectTypesDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "DeleteEnterpriseProjectTypesServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteEnterpriseProjectTypes(System.Guid[] enterpriseProjectTypeUid);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/SetWorkfl" +
                     "owStageStatusInformation",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/SetWorkfl" +
                          "owStageStatusInformationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "SetWorkflowStageStatusInformationServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "SetWorkflowStageStatusInformationDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void SetWorkflowStageStatusInformation(System.Guid projUid, System.Guid workflowStageUid,
            string statusInformation, int stageStatusValue, bool append);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdatePro" +
                     "jectWorkflow",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/UpdatePro" +
                          "jectWorkflowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateProjectWorkflowDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "UpdateProjectWorkflowServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdateProjectWorkflow(System.Guid projectUid, System.Guid enterpriseProjectTypeUid);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadStrat" +
                     "egicImpactBehaviorForCurrentWorkflowStage",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadStrat" +
                          "egicImpactBehaviorForCurrentWorkflowStageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadStrategicImpactBehaviorForCurrentWorkflowStageServerExecutionFaultFault",
            Name = "ServerExecutionFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadStrategicImpactBehaviorForCurrentWorkflowStageDefaultServerFaultFault",
            Name = "DefaultServerFault", Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        int ReadStrategicImpactBehaviorForCurrentWorkflowStage(System.Guid projectUid);

        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/QueueUpda" +
                     "teProjectWorkflows",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/QueueUpda" +
                          "teProjectWorkflowsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "QueueUpdateProjectWorkflowsDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "QueueUpdateProjectWorkflowsServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void QueueUpdateProjectWorkflows(WorkflowDataSet dsWorkflow);
        
        [System.ServiceModel.OperationContractAttribute(
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadAvail" +
                     "ableEnterpriseProjectTypes",
            ReplyAction = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/ReadAvail" +
                          "ableEnterpriseProjectTypesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof (DefaultServerFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadAvailableEnterpriseProjectTypesDefaultServerFaultFault", Name = "DefaultServerFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.FaultContractAttribute(typeof (ServerExecutionFault),
            Action = "http://schemas.microsoft.com/office/project/server/webservices/Workflow/Workflow/" +
                     "ReadAvailableEnterpriseProjectTypesServerExecutionFaultFault", Name = "ServerExecutionFault",
            Namespace = "http://Microsoft.Office.Project.Interfaces/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        WorkflowDataSet ReadAvailableEnterpriseProjectTypes();

    }
}
